### ISSUE TITLE
Similarities with ara and opportunities for collaboration

### ISSUE THREAD

**Issue by dmsimard** [tnt4brain/ansible-logging-to-db#1]
Hi o/

I saw your comment about this project in https://github.com/ansible/community/issues/546#issuecomment-945181857 but since it's not an issue meant for discussions I thought I could create an issue here instead.

I was wondering if you knew about ara: https://github.com/ansible-community/ara ?
It leverages a callback for saving the execution results to sqlite, mysql and postgresql and then provides an API for querying results.

There's a live demo here: https://demo.recordsansible.org/ (API: https://demo.recordsansible.org/api/v1/)

I thought that perhaps there might be an opportunity to collaborate ?

Let me know !

**Comment by tnt4brain** [comment]
Hi @dmsimard :-)

Sorry for being late with response, my repos get attention quite rarely.

Yes, I've seen the ARA back in 2017 while was looking for something alike. It was not considered as an option due to additional ops burden (webserver, storage, HA support absence, etc.)

I have kicked the tyres of the demo instance - it looks more or less feature-packed and complete. What can I help the project with?

**Comment by tnt4brain** [comment]
Seems like stale one.
